### PR TITLE
Automate PyPI packaging

### PR DESCRIPTION
**Pull request by pllim**
Automate PyPI release. Looks like there is already a token set, but somehow no workflow defined. Hmm!

### CODE REVIEW

**Comment by pllim** [comment]
p.s. I don't think Action runs for forks anymore, though it used to. Not sure how to test it without merging first. I simply copied this over from `pytest-doctestplus`

**Comment by pllim** [comment]
I also activated Zenodo webhook to upload to Zenodo on *GitHub Release* (their default behavior) even though this workflow activates on tag. Won't have the DOI until the next release happens.

**Review by saimn — APPROVED** [review]
If the token is already there (I must have added it when doing the other packages) then all good!

**Comment by pllim** [comment]
Well, that's weird. I published a release but it didn't kick off on the tag event. I'll give it a few in case there is a lag server side though GitHub status reporting green. 🤷 

This workflow worked for `pytest-doctestplus`.

**Comment by pllim** [comment]
Might have to manual release this one and figure out the automation next time. It is already pushed to Zenodo, so retag will be a pain.

**Comment by pllim** [comment]
See #46

**Pull request merged**
