### PR TITLE
Undo adding of pytest-mock 

### PR DESCRIPTION
**Pull request by pllim**
Is this what you meant in #32, @mhvk? It appears that `pytest-mock` was just added by @Cadair in #31.

### CODE REVIEW

**Comment by Cadair** [comment]
~:( but but why?~

commented on #32

**Comment by Cadair** [comment]
I am hard :-1: on this, this is a zero cost addition which helps sunpy out.

**Comment by bsipocz** [comment]
agree with @Cadair here. Unless there is a concrete issue that `pytest-mock` causes, I don't see why it should be removed.

**Comment by pllim** [comment]
Given that #32 is closed, I am closing this as well.

**Pull request closed without merging**
